version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (RabbitMQ client connections)
      - "15672:15672"   # HTTP (management UI)
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: devpass
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge



# RUN MESSAGE BROKER (RABBITMQ): $ docker-compose -f messageBroker.yaml up -d